#ifndef REGISTER_OPCODE

#error "REGISTER_OPCODE() not defined"

#endif

srsvm_word code = 0;

REGISTER_OPCODE(code++, NOP, 0, 0);
REGISTER_OPCODE(code++, HALT, 0, 1);

code += 5;

REGISTER_OPCODE(code++, CJMP_BACK, 1, 1); 
REGISTER_OPCODE(code++, CJMP_FORWARD, 1, 1); 

REGISTER_OPCODE(code++, CJMP_BACK_IF, 2, 2); 
REGISTER_OPCODE(code++, CJMP_FORWARD_IF, 2, 2); 

REGISTER_OPCODE(code++, CJMP_BACK_ERR, 2, 2); 
REGISTER_OPCODE(code++, CJMP_FORWARD_ERR, 2, 2); 

REGISTER_OPCODE(code++, JMP, 1, 1);
REGISTER_OPCODE(code++, JMP_OFF, 1, 1);

REGISTER_OPCODE(code++, JMP_IF, 2, 2);
REGISTER_OPCODE(code++, JMP_OFF_IF, 2, 2);

REGISTER_OPCODE(code++, JMP_ERR, 2, 2);
REGISTER_OPCODE(code++, JMP_OFF_ERR, 2, 2);

code += 8;

REGISTER_OPCODE(code++, ARGC, 1, 1);
REGISTER_OPCODE(code++, ARGV, 2, 2);

code += 2;

REGISTER_OPCODE(code++, LOAD_CONST, 2, 3);
REGISTER_OPCODE(code++, LOAD, 3, 4);
//REGISTER_OPCODE(10, LOAD_OFFSET, 4, 5);

code += 2;

REGISTER_OPCODE(code++, STORE, 3, 4);
//REGISTER_OPCODE(12, STORE_OFFSET, 4, 5);

code += 2;

REGISTER_OPCODE(code++, ALLOC, 2, 2);
REGISTER_OPCODE(code++, FREE, 1, 1);

code += 4;

REGISTER_OPCODE(code++, MOD_LOAD, 2, 2);
REGISTER_OPCODE(code++, MOD_UNLOAD, 1, 1);
REGISTER_OPCODE(code++, MOD_OP, 2, MAX_INSTRUCTION_ARGS);

REGISTER_OPCODE(code++, CMOD_LOAD, 3, 3);
REGISTER_OPCODE(code++, CMOD_UNLOAD, 1, 1);
REGISTER_OPCODE(code++, CMOD_OP, 2, MAX_INSTRUCTION_ARGS);

REGISTER_OPCODE(code++, MOD_UNLOAD_ALL, 0, 0);

code += 2;

/*REGISTER_OPCODE(code++, THREAD_START, 2, 2);
REGISTER_OPCODE(code++, THREAD_JOIN, 1, 1); */

code += 8;

REGISTER_OPCODE(code++, SLEEP, 1, 1);

code += 16;

REGISTER_OPCODE(code++, INCR, 1, 1);
REGISTER_OPCODE(code++, DECR, 1, 1);

code += 8;

REGISTER_OPCODE(code++, WORD_EQ, 3, 3);

code += 16;

REGISTER_OPCODE(code++, PUTS, 1, 1);
