#ifndef REGISTER_OPCODE

#error "REGISTER_OPCODE() not defined"

#endif

REGISTER_OPCODE(0, NOP, 0, 0);
REGISTER_OPCODE(1, HALT, 0, 1);

REGISTER_OPCODE(5, ALLOC, 2, 2);
REGISTER_OPCODE(6, FREE, 1, 1);

REGISTER_OPCODE(7, LOAD_CONST, 2, 3);
REGISTER_OPCODE(8, LOAD, 3, 4);
//REGISTER_OPCODE(9, LOAD_STR, 2, 2);
//REGISTER_OPCODE(10, LOAD_OFFSET, 4, 5);

REGISTER_OPCODE(10, STORE, 3, 4);
//REGISTER_OPCODE(11, STORE_STR, 3, 3);
//REGISTER_OPCODE(12, STORE_OFFSET, 4, 5);


REGISTER_OPCODE(15, MOD_LOAD, 2, 2);
REGISTER_OPCODE(16, MOD_UNLOAD, 1, 1);
REGISTER_OPCODE(17, MOD_OP, 2, MAX_INSTRUCTION_ARGS);

REGISTER_OPCODE(1337, PUTS, 1, 1);
